const menu_data = [
  {
    id: 1,
    mega_menu: false,
    has_dropdown: false,
    title: "Home",
    link: "/",
    active: "active",
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "About",
    link: "/about",
    active: "",
  },
  {
    id: 3,
    mega_menu: false,
    has_dropdown: true,
    title: "Department",
    link: "/service-3",
    active: "",
    sub_menus: [
      { link: "/obg", title: "Obstetrics & Gynaecology" },
      { link: "/skincosmetology", title: "Skin & Cosmetology" },
      { link: "/generalmedicine", title: "General Medicine" },
      { link: "/generalsurgery", title: "General Surgery" },
      { link: "/diabetology", title: "Diabetology" },
      { link: "/ophthalmology", title: "Ophthalmology" },
      { link: "/orthopaedics", title: "Orthopaedics" },
      { link: "/paediatrics", title: "Paediatrics" },
      { link: "/cardiology", title: "Cardiology" },
      { link: "/neurology", title: "Neurology" },
      { link: "/psychiatry", title: "Psychiatry" },
      { link: "/urology", title: "Urology" },
      { link: "/ent", title: "ENT" },
    ],
  },
  {
    id: 4,
    mega_menu: false,
    has_dropdown: true,
    title: "Facility",
    link: "/service",
    active: "",
    sub_menus: [
      { link: "/inpatient-services", title: "Inpatient Services" },
      {
        link: "/advanced-laboratory-services",
        title: "Advanced Laboratory Services",
      },
      { link: "/ultrasound-scanning", title: "Ultrasound Scanning" },
      { link: "/x-ray", title: "X-Ray" },
      { link: "/physiotheraphy", title: "Physiotheraphy" },
      { link: "/ecg", title: "ECG" },
      { link: "/ambulance-services", title: "Ambulance Services" },
      { link: "/pharmacy", title: "Pharmacy" },
      { link: "/surgical-center", title: "Surgical Center" },
      { link: "/laparoscopy", title: "Laparoscopy" },
    ],
  },
  {
    id: 6,
    mega_menu: false,
    has_dropdown: false,
    title: "Blog",
    link: "/blog",
    active: "",
  },
  {
    id: 7,
    mega_menu: false,
    has_dropdown: false,
    title: "Contact",
    link: "/contact",
    active: "",
  },
];
export default menu_data;
