import Head from "next/head";

const SEO = ({ pageTitle }) => (
  <>
    <Head>
      <title>{pageTitle && `Deepasri Multispecialities Hospital`}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta
        name="google-site-verification"
        content="xQQh8EhPNF7aSIvRuLSMuGNtf8MO0oxLxai3Q7FwccY"
      />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="/assets/photo/logomin.png" />
    </Head>
  </>
);

export default SEO;
